/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Start_Reg.h>
#include <Vin0.h>
#include <Vin0_aliases.h>
#include <LCD.h>
#include <Vin2.h>
#include <Vin2_aliases.h>
#include <EOCpin.h>
#include <EOCpin_aliases.h>
#include <SOCpin.h>
#include <SOCpin_aliases.h>
#include <Vin6.h>
#include <Vin6_aliases.h>
#include <DMA_ADC2Mem_dma.h>
#include <Count0.h>
#include <Count0_aliases.h>
#include <ChannelSelect.h>
#include <ChannelSelect_aliases.h>
#include <Vin5.h>
#include <Vin5_aliases.h>
#include <Vin4.h>
#include <Vin4_aliases.h>
#include <Vin3.h>
#include <Vin3_aliases.h>
#include <Vin7.h>
#include <Vin7_aliases.h>
#include <Vin8.h>
#include <Vin8_aliases.h>
#include <Vin9.h>
#include <Vin9_aliases.h>
#include <VinA.h>
#include <VinA_aliases.h>
#include <VinB.h>
#include <VinB_aliases.h>
#include <VinC.h>
#include <VinC_aliases.h>
#include <Delay_PWM.h>
#include <Count3.h>
#include <Count3_aliases.h>
#include <Count2.h>
#include <Count2_aliases.h>
#include <Count1.h>
#include <Count1_aliases.h>
#include <Vin1.h>
#include <Vin1_aliases.h>
#include <VinD.h>
#include <VinD_aliases.h>
#include <VinE.h>
#include <VinE_aliases.h>
#include <VinF.h>
#include <VinF_aliases.h>
#include <ADC.h>
#include <DMA_Mem2Mem_dma.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <ADC_AMux.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_IRQ.h>
#include <ADC_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

