/*******************************************************************************
* File Name: main.c
*
* Version: 1.00
*
* Description:
*   This is the source code for the DelSig_16Channel Example Project.
*	DelSig_16Channel Example Project intended to use as Creator starter design 
*	for PSoC 3/5LP devices. 
*
*   Note that this file contains the DMA_Config function as well.
*
********************************************************************************
* Copyright 2012, Cypress Semiconductor Corporation. All rights reserved.
* This software is owned by Cypress Semiconductor Corporation and is protected
* by and subject to worldwide patent and copyright laws and treaties.
* Therefore, you may use this software only as provided in the license agreement
* accompanying the software package from which you obtained this software.
* CYPRESS AND ITS SUPPLIERS MAKE NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
* WITH REGARD TO THIS SOFTWARE, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*******************************************************************************/
#include <project.h>
#include <device.h>

/* There are 16 input channels */
#define window_size (256u)

/* DMA Configuration for DMA_ADC2Mem */
#define DMA_ADC2Mem_BYTES_PER_BURST 4
#define DMA_ADC2Mem_REQUEST_PER_BURST 1
#define DMA_ADC2Mem_SRC_BASE (CYDEV_PERIPH_BASE)
#define DMA_ADC2Mem_DST_BASE (CYDEV_SRAM_BASE)

/* DMA Configuration for DMA_Mem2Mem */
#define DMA_Mem2Mem_BYTES_PER_BURST 4
#define DMA_Mem2Mem_REQUEST_PER_BURST 1
#define DMA_Mem2Mem_SRC_BASE (CYDEV_SRAM_BASE)
#define DMA_Mem2Mem_DST_BASE (CYDEV_SRAM_BASE)

/* DMA Configuration for DMA_ADC2Filter */
#define DMA_ADC2Filter_BYTES_PER_BURST 4
#define DMA_ADC2Filter_REQUEST_PER_BURST 1
#define DMA_ADC2Filter_SRC_BASE (CYDEV_PERIPH_BASE)
#define DMA_ADC2Filter_DST_BASE (CYDEV_PERIPH_BASE)

/* DMA Configuration for DMA_Filter2Mem */
#define DMA_Filter2Mem_BYTES_PER_BURST 4
#define DMA_Filter2Mem_REQUEST_PER_BURST 1
#define DMA_Filter2Mem_SRC_BASE (CYDEV_PERIPH_BASE)
#define DMA_Filter2Mem_DST_BASE (CYDEV_SRAM_BASE)

/* DMA Configuration for DMA_FilterMem2Mem */
#define DMA_FilterMem2Mem_BYTES_PER_BURST 4
#define DMA_FilterMem2Mem_REQUEST_PER_BURST 0
#define DMA_FilterMem2Mem_SRC_BASE (CYDEV_SRAM_BASE)
#define DMA_FilterMem2Mem_DST_BASE (CYDEV_SRAM_BASE)



/* Directive to place adc_temp at a particular location. The location is 
chosen as a multiple of 4 bytes (even boundary) */

#if(CY_PSOC3)	
		int32 xdata adc_temp _at_ 0x100; 
#else /* PSoC5 being used */
	int32 adc_temp;
    int32 filter_temp;
#endif

#if(CY_PSOC3)
	int32 xdata result[window_size] _at_ 0x200;
#else /* PSoC5 being used */
	int32 result[window_size];
    int32 Filtered_result[window_size];
#endif



void DMA_Config(void);


/*******************************************************************************
* Function Name: main
********************************************************************************
*
* Summary:
*  main() performs following functions:
*  1: Starts the components
*  2: Calls function DMA_Config to setup the DMA.
*  3: Starts ADC continuous conversion.
*  4: Gets the converted result and displays it in LCD. Also displays VDAC data
*     register value on LCD.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void main()
{
	int16 temp;
	

    LCD_Start();
    ADC_Start();
	
	 /* Disable ADC interrupts */
	ADC_IRQ_Disable();

	/*Change the ADC coherent key to high byte*/
	ADC_DEC_COHER_REG |= ADC_DEC_SAMP_KEY_HIGH;

	/*Start ADC conversions*/
	ADC_StartConvert();

    Filter_SetDalign(Filter_STAGEA_DALIGN | Filter_HOLDA_DALIGN | Filter_HOLDB_DALIGN | Filter_STAGEB_DALIGN,Filter_DISABLED);
    Filter_SetCoherency(Filter_STAGEA_COHER | Filter_HOLDA_COHER | Filter_STAGEB_COHER | Filter_HOLDB_COHER,Filter_KEY_HIGH);
    Filter_SetCoherency(Filter_CHANNEL_A,Filter_KEY_HIGH);  
    Filter_SetCoherency(Filter_CHANNEL_B,Filter_KEY_HIGH);

    Filter_Start();
    DMA_Config();

     CYGlobalIntEnable;  /* Uncomment this line to enable global interrupts. */
    for(;;)
    {
        LCD_ClearDisplay();
        LCD_Position(0u, 0u);
		temp = ADC_CountsTo_mVolts(adc_temp);
		LCD_PrintNumber(temp);
		
    }
}


/*******************************************************************************
* Function Name:  DMA_Config
********************************************************************************
*
* Summary:
*    Code generated by the DMA Wizard.
*
*    DMA_Config() performs following functions:
*  1: Initializes the DMA channel
*  2: Allocates Transfer Descriptors
*  3: Configures the TD.
*  4: Sets source and destination address for this TD.
*  5: Initializes the TD.
*  6: Enables the DMA channel.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void DMA_Config()
{
/* Variable declarations for DMA_ADC2Mem */
uint8 DMA_ADC2Mem_Chan;
uint8 DMA_ADC2Mem_TD[1];

/* Variable declarations for DMA_Mem2Mem */
uint8 DMA_Mem2Mem_Chan;
uint8 DMA_Mem2Mem_TD[1];

/* Variable declarations for DMA_ADC2Filter */
uint8 DMA_ADC2Filter_Chan;
uint8 DMA_ADC2Filter_TD[1];

/* Variable declarations for DMA_Filter2Mem */
uint8 DMA_Filter2Mem_Chan;
uint8 DMA_Filter2Mem_TD[1];

/* Variable declarations for DMA_Filter2Filter */
uint8 DMA_FilterMem2Mem_Chan;
uint8 DMA_FilterMem2Mem_TD[1];


/*DMA_ADC2Mem*/
DMA_ADC2Mem_Chan = DMA_ADC2Mem_DmaInitialize(DMA_ADC2Mem_BYTES_PER_BURST, DMA_ADC2Mem_REQUEST_PER_BURST, 
    HI16(DMA_ADC2Mem_SRC_BASE), HI16(DMA_ADC2Mem_DST_BASE));
DMA_ADC2Mem_TD[0] = CyDmaTdAllocate();
CyDmaTdSetConfiguration(DMA_ADC2Mem_TD[0], 4, DMA_ADC2Mem_TD[0], DMA_ADC2Mem__TD_TERMOUT_EN | TD_INC_SRC_ADR);
CyDmaTdSetAddress(DMA_ADC2Mem_TD[0], LO16((uint32)ADC_DEC_SAMP_PTR), LO16((uint32)Filter_STAGEA_PTR));
CyDmaChSetInitialTd(DMA_ADC2Mem_Chan, DMA_ADC2Mem_TD[0]);
CyDmaChEnable(DMA_ADC2Mem_Chan, 1);


/*DMA_Mem2Mem*/
DMA_Mem2Mem_Chan = DMA_Mem2Mem_DmaInitialize(DMA_Mem2Mem_BYTES_PER_BURST, DMA_Mem2Mem_REQUEST_PER_BURST, 
    HI16(DMA_Mem2Mem_SRC_BASE), HI16(DMA_Mem2Mem_DST_BASE));
DMA_Mem2Mem_TD[0] = CyDmaTdAllocate();
CyDmaTdSetConfiguration(DMA_Mem2Mem_TD[0], window_size*4, DMA_Mem2Mem_TD[0], TD_INC_DST_ADR);
CyDmaTdSetAddress(DMA_Mem2Mem_TD[0], LO16((uint32)&adc_temp), LO16((uint32)result));
CyDmaChSetInitialTd(DMA_Mem2Mem_Chan, DMA_Mem2Mem_TD[0]);
CyDmaChEnable(DMA_Mem2Mem_Chan, 1);


/*DMA_ADC2Filter*/
DMA_ADC2Filter_Chan = DMA_ADC2Filter_DmaInitialize(DMA_ADC2Filter_BYTES_PER_BURST, DMA_ADC2Filter_REQUEST_PER_BURST, 
    HI16(DMA_ADC2Filter_SRC_BASE), HI16(DMA_ADC2Filter_DST_BASE));
DMA_ADC2Filter_TD[0] = CyDmaTdAllocate();
CyDmaTdSetConfiguration(DMA_ADC2Filter_TD[0], 4, DMA_ADC2Filter_TD[0], DMA_ADC2Filter__TD_TERMOUT_EN | TD_INC_SRC_ADR);
CyDmaTdSetAddress(DMA_ADC2Filter_TD[0], LO16((uint32)ADC_DEC_SAMP_PTR), LO16((uint32)&adc_temp));
CyDmaChSetInitialTd(DMA_ADC2Filter_Chan, DMA_ADC2Filter_TD[0]);
CyDmaChEnable(DMA_ADC2Filter_Chan, 1);


/*DMA_Filter2Mem*/
DMA_Filter2Mem_Chan = DMA_Filter2Mem_DmaInitialize(DMA_Filter2Mem_BYTES_PER_BURST, DMA_Filter2Mem_REQUEST_PER_BURST, 
    HI16(DMA_Filter2Mem_SRC_BASE), HI16(DMA_Filter2Mem_DST_BASE));
DMA_Filter2Mem_TD[0] = CyDmaTdAllocate();
CyDmaTdSetConfiguration(DMA_Filter2Mem_TD[0], window_size*4, DMA_Filter2Mem_TD[0], DMA_Filter2Mem__TD_TERMOUT_EN | TD_INC_DST_ADR );
CyDmaTdSetAddress(DMA_Filter2Mem_TD[0], LO16((uint32)Filter_HOLDA_PTR), LO16((uint32)&filter_temp));
CyDmaChSetInitialTd(DMA_Filter2Mem_Chan, DMA_Filter2Mem_TD[0]);
CyDmaChEnable(DMA_Filter2Mem_Chan, 1);

/*DMA_FilterMem2Mem*/
DMA_FilterMem2Mem_Chan = DMA_FilterMem2Mem_DmaInitialize(DMA_FilterMem2Mem_BYTES_PER_BURST, DMA_FilterMem2Mem_REQUEST_PER_BURST, 
    HI16(DMA_FilterMem2Mem_SRC_BASE), HI16(DMA_FilterMem2Mem_DST_BASE));
DMA_Mem2Mem_TD[0] = CyDmaTdAllocate();
CyDmaTdSetConfiguration(DMA_FilterMem2Mem_TD[0], window_size*4, DMA_FilterMem2Mem_TD[0], TD_INC_DST_ADR | TD_INC_SRC_ADR | DMA_FilterMem2Mem__TD_TERMOUT_EN);
CyDmaTdSetAddress(DMA_FilterMem2Mem_TD[0], LO16((uint32)&filter_temp), LO16((uint32)Filtered_result));
CyDmaChSetInitialTd(DMA_FilterMem2Mem_Chan, DMA_FilterMem2Mem_TD[0]);
CyDmaChEnable(DMA_FilterMem2Mem_Chan, 1);
}


/* [] END OF FILE */








